name: "Deploy to A.D.S. Games"
description: "Deploy files to storage bucket, and send a release message"

inputs:
  project-id:
    description: "A.D.S. Games Game Name"
    required: true
  version:
    description: "Version to Release"
    required: false
  bucket-access-key:
    description: "Access key for accessing S3"
    required: true
  bucket-secret-key:
    description: "Secret key for accessing S3"
    required: true
  build-dir:
    description: "Folder to upload"
    required: true
    default: build/
  platform:
    description: "Game Platform"
    required: true
  api-key:
    description: "A.D.S. Games API key"
    required: true
  entry:
    description: "Entry point for web builds"
    required: false
    default: index.html

runs:
  using: "composite"
  steps:
    - name: Set up S3cmd cli tool
      uses: s3-actions/s3cmd@v1.5.0
      with:
        provider: linode
        region: us-east-1
        access_key: ${{ inputs.bucket-access-key }}
        secret_key: ${{ inputs.bucket-secret-key }}

    - name: Deploy game
      shell: bash
      run: ${{ github.action_path }}/deploy.sh
      env:
        VERSION: ${{ inputs.version }}
        PLATFORM: ${{ inputs.platform }}
        PROJECT_ID: ${{ inputs.project-id }}
        ENTRY: ${{ inputs.entry }}
        BUILD_DIR: ${{ inputs.build-dir }}
        API_KEY: ${{ inputs.api-key }}
        BUILD_COMMAND: ${{ inputs.build-command }}
